export const funcContent = [
  { name: 'change', desc: '选中选项或输入的值变化时，调用此函数，一个参数： value为变化的值', },
  { name: 'callBack', desc: '数据选中回调方法，方法有两个参数：value为选中会写的值对应设置中\'选中组件值\'，item为选中的行数据', },
  { name: 'search', desc: '方法参数vaule，为组件录入的数据，静态数据设值示例：this.dataSource = staticData;远程请求已将请求参数封装到param中,请求示例： Base.submit(null, {url:\'XXXXXX\',data:param}).then(res=>{this.dataSource = res.data.list})', },
  { name: 'blur', desc: '移除焦点时调用', },
  { name: 'beforeChange', desc: '数据改变之前调用', },
  { name: 'focus', desc: '获取焦点时调用', },
  { name: 'click', desc: '点击组件时调用此函数', },
  { name: 'ok', desc: '点击确定回调，一个参数：e为 \'$event\'对象', },
  { name: 'cancel', desc: '点击取消按钮的回调，一个参数：e为 \'$event\'对象', },
  { name: 'onload', desc: '加载数据时调用', }
]
const responseHandleStr = '\r\n' + '// ------函数开始------'
const commonAfterCode = '\')' + '\r\n' + '// ------函数结束------' + '\r\n'
const noParamAfterCode = ')' + '\r\n' + '// ------函数结束------' + '\r\n'
// 1、当前事件参数填写类型param说明: 'id' | 'value' | 'id, value' ---- 默认 'id'
//  null, 不需要填写参数
//  'id'  id数据下拉选，只能进行表单项id选择
//  'tableId'  表格id数据下拉选，只能进行表格组件id选择
//  'containerId'  容器id数据下拉选，只能进行容器型组件id选择
//  'value'   输入框，根据事件方法要求，自行输入满足格式的内容
//  'flag'   true|false 下拉选
//  'id, value'  当前事件传入参数：id下拉选 和 value值输入框
// 2、当前事件参数传入时组装类型paramType说明: 'String' | 'Object' | 'Array' ---- 默认 'String'

// 3、填写方式包含id、containerId选择时，需要填写下拉选单选or多选方式 isMultiple true为多选，false为单选---默认 false
// 4、placeHolder1默认为：请选择组件id，单个组件的提示信息需要自定义时，请配置参数placeHolder1, id, value时，需配置placeHolder1和 placeHolder2
export const quickMethodCodeList = [
  {
    name: '后端请求',
    value: 'submit',
    param: null,
    beforeCode: '',
    afterCode: '',
    type: 'submit',
    isCommon: true,
    defaultEventType: '',
  },
  {
    name: '获取组件对象',
    value: 'getObj',
    param: 'id',
    desc: '选择需要获取目标对象的组件(id)',
    beforeCode: responseHandleStr + '\r\n this_.getObj(\'',
    afterCode: commonAfterCode,
    type: 'get',
    isCommon: true,
    defaultEventType: '',
  },
  {
    name: '组件展示',
    value: 'showObj',
    param: 'id',
    isMultiple: true,
    desc: '请选择需要展示的组件(id1,id2,id3)',
    beforeCode: responseHandleStr + '\r\n this_.showObj(\'',
    afterCode: commonAfterCode,
    type: 'set',
    isCommon: true,
    defaultEventType: '',
  },
  {
    name: '组件隐藏',
    value: 'hideObj',
    param: 'id',
    isMultiple: true,
    desc: '请选择需要隐藏的组件(id1,id2,id3)',
    beforeCode: responseHandleStr + '\r\n this_.hideObj(\'',
    afterCode: commonAfterCode,
    type: 'set',
    isCommon: true,
    defaultEventType: '',
  },
  {
    name: '组件刷新',
    value: 'updateComp',
    param: 'id',
    desc: '选择需要刷新的组件(id)',
    beforeCode: responseHandleStr + '\r\n this_.updateComp(\'',
    afterCode: commonAfterCode,
    type: 'set',
    isCommon: true,
    defaultEventType: '',
  },
  {
    name: '新增大表格行',
    value: 'getInsertRecords',
    param: 'tableId',
    desc: '请选择需要新增表格行数据的大表格组件(id)',
    beforeCode: responseHandleStr + '\r\n' +
          '// 若新增行需要从后端获取行主键号，则将下面代码写在回调函数successCallBack，回调对象替换掉insert方法的空对象 {} ' + '\r\n' + '// 获取表格对象' + '\r\n' +
        'let tableObj = this_.getObj(\'',
    afterCode: '\').getTable();' + '\r\n' +
          'tableObj.insert({})' + '\r\n' +
          '// 激活新增行' + '\r\n' +
          'tableObj.setActiveRow(tableObj.getInsertRecords()[0])' + '\r\n' +
          '// ------函数结束------' + '\r\n',
    type: 'set',
    isCommon: true,
    defaultEventType: '',
  },
  {
    name: '设置页面表格数据',
    value: 'setTableData',
    param: 'tableId, value',
    desc: '该方法有两个参数，id: 选择表格组件(id)，value:设置的值【Array】或者变量名',
    placeHolder2: '请输入表格对应的value值，例如：[] 或者变量名 \'tableData\'',
    beforeCode: responseHandleStr + '\r\n this_.setTableData(',
    afterCode: noParamAfterCode,
    type: 'set',
    isCommon: false,
    defaultEventType: '',
  },
  {
    name: '设置表单项非必填',
    value: 'setNotRequired',
    param: 'id',
    isMultiple: true,
    desc: '请选择需要设置非必填的组件(id1,id2,id3)',
    beforeCode: responseHandleStr + '\r\n this_.setNotRequired(\'',
    afterCode: commonAfterCode,
    type: 'set',
    isCommon: false,
    defaultEventType: '',
  },
  {
    name: '设置表单项必填',
    value: 'setRequired',
    param: 'id',
    isMultiple: true,
    desc: '请选择需要设置必填的组件(id1,id2,id3)',
    beforeCode: responseHandleStr + '\r\n this_.setRequired(\'',
    afterCode: commonAfterCode,
    type: 'set',
    isCommon: false,
    defaultEventType: '',
  },
  {
    name: '设置单个表单项值',
    value: 'setValue',
    param: 'id, value',
    placeHolder2: '请输入value值，例如: \'123\'',
    desc: '该方法有两个参数，id: 选择组件(id)，value: 组件对应的值',
    beforeCode: responseHandleStr + '\r\n this_.setValue(',
    afterCode: noParamAfterCode,
    type: 'set',
    isCommon: true,
    defaultEventType: '',
  },
  {
    name: '设置多个表单项值',
    value: 'setValues',
    param: 'id, value',
    paramType: 'Object',
    isMultiple: true,
    placeHolder2: '请输入value值,多个值以;隔开,例如: \'张三\';\'李四\'',
    desc: '该方法参数value值为多个时将根据id顺序进行对应，传入方法时为{id: value}对象',
    beforeCode: responseHandleStr + '\r\n this_.setValues(',
    afterCode: noParamAfterCode,
    type: 'set',
    isCommon: true,
    defaultEventType: '',
  },
  {
    name: '设置页面某个变量',
    value: 'setParam',
    param: 'value',
    desc: '该方法有两个参数，key:字段变量,value:字段值。例如：\'name\', \'333\'，如果值是变量的话：\'name\',nameStr 。',
    placeHolder2: '请输入key和对应的value值',
    beforeCode: responseHandleStr + '\r\n this_.setParam(',
    afterCode: noParamAfterCode,
    type: 'set',
    isCommon: false,
    defaultEventType: '',
  },
  {
    name: '批量设置页面变量',
    value: 'setParams',
    param: 'value',
    desc: '该方法的参数类型为对象，例如：{key: val}',
    placeHolder2: '请输入对象或对象名称，例如: listObj 或者 {\'name\':\'张三\'}',
    beforeCode: responseHandleStr + '\r\n this_.setParams(',
    afterCode: noParamAfterCode,
    type: 'set',
    isCommon: true,
    defaultEventType: '',
  },
  {
    name: '设置步骤条当前步骤信息',
    value: 'changeStepsCurrent',
    param: 'id, value',
    desc: '该方法有两个参数，id:组件id,obj:{current: 当前步骤, status: 当前步骤状态}。例如：\'id1\', {\'current\':2, \'status\':\'process\'}',
    placeHolder2: '请输入修改的步骤信息',
    beforeCode: responseHandleStr + '\r\n this_.changeStepsCurrent(',
    afterCode: noParamAfterCode,
    type: 'set',
    isCommon: false,
    defaultEventType: '',
  },
  {
    name: '设置弹窗确认按钮是否隐藏',
    value: 'setModalSaveHide',
    param: 'id, flag',
    desc: '该方法有两个参数，id: 选择组件(id)，flag(boolean类型):确认按钮是否隐藏',
    placeHolder2: '请选择否隐藏,隐藏true/不隐藏false',
    beforeCode: responseHandleStr + '\r\n this_.setModalSaveHide(',
    afterCode: noParamAfterCode,
    type: 'set',
    isCommon: false,
    defaultEventType: '',
  },
  {
    name: '重置组合输入框的值',
    value: 'resetInputGroupValue',
    param: 'inputGroupId',
    isMultiple: true,
    desc: '请选择需要重置值的组合输入框组件(id1,id2,id3)',
    beforeCode: responseHandleStr + '\r\n this_.resetInputGroupValue(\'',
    afterCode: commonAfterCode,
    type: 'set',
    isCommon: true,
    defaultEventType: '',
  },
  {
    name: '重置表单',
    value: 'handleReset',
    param: null,
    desc: '该方法无参数，直接调用即可',
    beforeCode: responseHandleStr + '\r\n this_.handleReset(',
    afterCode: noParamAfterCode,
    type: 'set',
    isCommon: false,
    defaultEventType: '',
  },
  {
    name: '重置部分表单项的值',
    value: 'resetFields',
    param: 'partId',
    isMultiple: true,
    paramType: 'Array',
    desc: '请选择需要重置值的表单项([\'id1\',\'id2\',\'id3\'])',
    beforeCode: responseHandleStr + '\r\n this_.resetFields(',
    afterCode: noParamAfterCode,
    type: 'set',
    isCommon: true,
    defaultEventType: '',
  },
  {
    name: '设置组件只读',
    value: 'setReadonly',
    param: 'id',
    isMultiple: true,
    desc: '请选择需要设置只读的组件(id1,id2,id3)',
    beforeCode: responseHandleStr + '\r\n this_.setReadonly(\'',
    afterCode: commonAfterCode,
    type: 'set',
    isCommon: false,
    defaultEventType: '',
  },
  {
    name: '设置所有组件是否禁用',
    value: 'setAllDisable',
    param: 'flag',
    placeHolder1: '请选择禁用true/可用false',
    desc: '该方法参数为flag，是boolean类型，值为【true】实现组件禁用，值为【false】，全部组件可用。注意：设置参数值为【true】，会禁用页面上全部有禁用属性的组件。',
    beforeCode: responseHandleStr + '\r\n this_.setAllDisable(',
    afterCode: noParamAfterCode,
    type: 'set',
    isCommon: false,
    defaultEventType: '',
  },
  {
    name: '设置组件禁用',
    value: 'setDisable',
    param: 'id',
    isMultiple: true,
    desc: '该方法的参数为id组成的字符串，例如：id1,id2（设置按钮组中按钮禁用时,id为`按钮组组件id_当前按钮顺序数`）',
    beforeCode: responseHandleStr + '\r\n this_.setDisable(\'',
    afterCode: commonAfterCode,
    type: 'set',
    isCommon: true,
    defaultEventType: '',
  },
  {
    name: '设置组件可用',
    value: 'setEnable',
    param: 'id',
    isMultiple: true,
    desc: '该方法的参数为id组成的字符串，例如：id1,id2（设置按钮组中按钮可用时,id为`按钮组组件id_当前按钮顺序数`）',
    beforeCode: responseHandleStr + '\r\n this_.setEnable(\'',
    afterCode: commonAfterCode,
    type: 'set',
    isCommon: true,
    defaultEventType: '',
  },
  {
    name: '切换tabs组件选中tab页',
    value: 'changeActiveKey',
    param: 'tabId, value',
    desc: '该方法有两个参数，id:组件id,key:标签页的key值',
    placeHolder2: '请输入标签页的key值,例如\'key1\'',
    beforeCode: responseHandleStr + '\r\n this_.changeActiveKey(',
    afterCode: noParamAfterCode,
    type: 'set',
    isCommon: false,
    defaultEventType: '',
  },
  {
    name: '获取页面某个变量',
    value: 'getParam',
    param: 'value',
    desc: '该方法参数为变量的key值',
    placeHolder2: '请输入变量名称,例如: name',
    beforeCode: responseHandleStr + '\r\n this_.getParam(\'',
    afterCode: commonAfterCode,
    type: 'get',
    isCommon: true,
    defaultEventType: '',
  },
  { name: '获取全部表单项值', value: 'getValues', param: null, desc: '该方法无参数，直接调用即可', beforeCode: responseHandleStr + '\r\n this_.getValues(', afterCode: noParamAfterCode, type: 'get', isCommon: true, defaultEventType: '', },
  { name: '获取单个表单项值', value: 'getValue', param: 'id', desc: '选择需要获取值的组件(id)', beforeCode: responseHandleStr + '\r\n this_.getValue(\'', afterCode: commonAfterCode, type: 'get', isCommon: true, defaultEventType: '', },
  { name: '获取验证通过的表单值', value: 'getValuesWithValid', param: null, desc: '该方法无参数，直接调用即可', beforeCode: responseHandleStr + '\r\n this_.getValuesWithValid(', afterCode: noParamAfterCode, type: 'get', isCommon: false, defaultEventType: '', },
  { name: '获取地址栏的参数值', value: 'fnGetUrlParam', param: 'value', desc: '该方法参数为url的参数名，如：taskId', placeHolder2: '请输入url的参数名', beforeCode: responseHandleStr + '\r\n this_.fnGetUrlParam(\'', afterCode: commonAfterCode, type: 'get', isCommon: false, defaultEventType: '', },
  { name: 'rpc组件回填刷新', value: 'refreshRpcAfter', param: 'id', isMultiple: true, desc: '该方法的参数为rpc组件id组成的字符串，例如：\'id1,id2\'}', beforeCode: responseHandleStr + '\r\n this_.refreshRpcAfter(\'', afterCode: commonAfterCode, type: 'set', isCommon: false, defaultEventType: '', },
  { name: '调用外层函数($bus/$emit)', value: 'emitMethod', param: 'value', desc: '该方法有多个参数，methodName:外层函数名称,arg1,arg2...:参数。例如：\'sendParam\', 123,\'aaa\'', placeHolder2: '请输入函数名称和参数信息', beforeCode: responseHandleStr + '\r\n this_.emitMethod(', afterCode: noParamAfterCode, type: 'set', isCommon: false, defaultEventType: '', },
  { name: '设置组件是否自动显示隐藏', value: 'setAutoShow', param: 'id, flag', isMultiple: true, desc: '该方法有两个参数，id:组件id,多个用逗号分隔, flag(boolean类型):是否让自动显示隐藏生效', placeHolder: '请输入组件id和是否隐藏的值', beforeCode: responseHandleStr + '\r\n this_.setAutoShow(', afterCode: noParamAfterCode, type: 'set', isCommon: false, },
  { name: '刷新组件，使组件的自动显示隐藏功能生效', value: 'loadAutoShow', param: 'flag', desc: '该方法有一个可选参数，isV(boolean类型):是否让自动显示隐藏生效,默认为true。例如：false', placeHolder2: '请选择否隐藏', beforeCode: responseHandleStr + '\r\n this_.loadAutoShow(', afterCode: noParamAfterCode, type: 'set', isCommon: false, defaultEventType: '', },
  { name: '复制组件，在目标组件后方插入', value: 'cloneObj', param: 'id', desc: '传入需要复制的组件id值，在该组件后方复制一个相同的组件', beforeCode: responseHandleStr + '\r\n this_.cloneObj(\'', afterCode: commonAfterCode, type: 'set', isCommon: true, defaultEventType: '', },
  {
    name: '批量获取组件ID',
    value: 'getFieldsId',
    param: 'containerId',
    desc: '获取所有组件ID，该方法有一个可选参数，containerId:容器类型组件ID，传入容器类型组件可以获取该容器内部所有组件ID。目前仅限于表单，抽屉，弹窗，DIV容器，动态表单，标签页，Border布局',
    beforeCode: responseHandleStr + '\r\n this_.getFieldsId(\'',
    afterCode: commonAfterCode,
    type: 'get',
    isCommon: false,
    defaultEventType: '',
  },
  {
    name: '获取动态表单值',
    value: 'getCardAddData',
    param: 'cardAddId',
    desc: '选择需要获取表单值的动态表单组件(id)',
    beforeCode: responseHandleStr + '\r\n this_.getCardAddData(\'',
    afterCode: commonAfterCode,
    type: 'get',
    isCommon: true,
    defaultEventType: '',
  },
  {
    name: '定制代码块',
    value: '',
    param: 'custom',
    funcName: '',
    desc: '自定义快捷函数：传入处理函数名称与参数，执行对应函数处理返回字符串；函数声明需在快捷函数拓展JS中定义。',
    placeHolder3: '输入函数名称',
    placeHolder2: '输入参数值,要求格式为字符串',
    beforeCode: '\r\n' + '// ------函数开始------' + '\r\n',
    afterCode: '\r\n' + '// ------函数结束------' + '\r\n',
    type: 'custom',
    isCommon: false,
    defaultEventType: '',
  },
  {
    name: '预定义函数的代码块',
    value: 'funcStr',
    param: 'value',
    desc: '该方法有一个可选参数，value:自定义的字符串内容',
    beforeCode: '\r\n' + '// ------函数开始------' + '\r\n',
    afterCode: '\r\n' + '// ------函数结束------' + '\r\n',
    handler: (this_, code) => {
      return code
    },
    type: 'func',
    isCommon: false,
    defaultEventType: 'click',
  }
]

export const requestFormData = 'let formData = this_.form.getFieldsValue(); // 表单数据 ' + '\r\n' + 'let value = this_.getParam(\'业务参数key\'); // 页面变量'
