export interface PropsDefinition {
  name: string;
  type: 'boolean' | 'string' | 'number' | 'object' | 'Function' | 'Array';
  defaultValue?: any;
  description?: string;
  options?: Array<Boolean | string | number>;
  required?: boolean;
  label?: string;
}

export interface ComponentProp {
  type: string,
  props: PropsDefinition[];
}
/**
 * 通用属性定义
 */
export const CommonProps: { [key: string]: PropsDefinition } = {
  type: {
    name: 'type',
    label: '组件类型',
    type: 'string',
    description: '组件类型，不可修改',
    required: true,
  },
  fieldDecoratorId: {
    name: 'fieldDecoratorId',
    label: '组件唯一标识符',
    type: 'string',
    description: '组件唯一标识符，自动生成，以字母开头的8位随机码（32进制）',
    required: true,
  },
  renderId: {
    name: 'renderId',
    label: '组件唯一标识符',
    type: 'string',
    description: '组件唯一标识符，自动生成，以字母开头的12位随机码（32进制）',
    required: true,
  },
  css: {
    name: 'css',
    type: 'string',
    description: 'CSS样式',
  },
  style: {
    name: 'style',
    type: 'string',
    description: '组件样式，示例："color:red;font-size:20px"',
  },
  display: {
    name: 'display',
    type: 'string',
    description: '是否显示组件，默认值："true"，可选值："false"和"true"',
    defaultValue: 'true',
    required: false,
    options: ['true', 'false'],
  },
  disabled: {
    name: 'disabled',
    type: 'boolean',
    description: '是否禁用输入框',
    required: false,
  },
  placeholder: {
    name: 'placeholder',
    type: 'string',
    description: '输入框占位提示文字',
    required: false,
  },
  required: {
    name: 'required',
    type: 'boolean',
    description: '是否必填',
    required: false,
  },
  label: {
    name: 'label',
    type: 'string',
    description: '组件显示名称',
    required: true,
  },
  initialValue: {
    name: 'initialValue',
    type: 'string',
    description: '默认值，类型根据组件类型而定',
    required: false,
  },
  message: {
    name: 'message',
    type: 'string',
    description: '验证提示信息，示例："请填写单行文本信息"/"请填写密码"',
    required: false,
  },
  rules: {
    name: 'rules',
    type: 'string',
    description: '自定义验证规则（转义的JSON字符串）',
    required: false,
  },
  extra: {
    name: 'extra',
    type: 'string',
    description: '额外描述信息，示例："我是额外信息，主要用于补充描述该项属性的填写注意事项"',
    required: false,
  },
  span: {
    name: 'span',
    type: 'number',
    description: '栅格占据列数，整个组件在外部容器中占的栅格，计算方式为 24 / 列数。默认值：8，可选值：1-24',
    required: true,
    defaultValue: 8,
  },
  tools: {
    name: 'tools',
    type: 'object',
    description: '工具配置，默认值：{}',
    required: true,
  },
  autoShow: {
    name: 'autoShow',
    type: 'boolean',
    description: '是否自动显示组件，默认值：false，可选值：false 和 true',
    required: true,
    defaultValue: false,
  },
  fieldsAlias: {
    name: 'fieldsAlias',
    type: 'string',
    description: '组件字段别名',
    required: false,
  },
  validateTrigger: {
    name: 'validateTrigger',
    type: 'Array',
    description: '触发验证的事件，可选值：["change", "blur"]，示例：["blur"]',
    required: false,
  },
  rules_object: {
    name: 'rules',
    type: 'object',
    description:
        "自定义验证规则（转义的JSON字符串），示例：[{\n pattern: '(^\\d{15}$)|(^\\d{17}(\\d|X|x)$)',\n message: '需要输入身份证号'\n}]",
    required: false,
  },
  allowClear: {
    name: 'allowClear',
    type: 'boolean',
    description: '是否允许清除 / 是否支持清空，默认值：true (在 rpc 中) / 无 (在 single-input, password 中)，可选值：false 和 true',
    required: false,
    defaultValue: true,
  },
  addonBefore: {
    name: 'addonBefore',
    type: 'string',
    description: '前置内容，用于 single-input, password 组件',
    required: false,
  },
  addonAfter: {
    name: 'addonAfter',
    type: 'string',
    description: '后置内容，用于 single-input, password 组件',
    required: false,
  },
  isRender: {
    name: 'isRender',
    type: 'string',
    description: '是否渲染元素，为 false 时元素不渲染，表单提交时不验证，可选值：false 和 true',
    required: false,
  },
  labelCol: {
    name: 'labelCol',
    type: 'number',
    description: '标签所占栅格，与 wrapperCol 属性合为 24，默认值：6，可选值：1-24',
    required: false,
    defaultValue: 6,
  },
  wrapperCol: {
    name: 'wrapperCol',
    type: 'number',
    description: '封装组件栅格，与 labelCol 合为 24，默认值：18，可选值：1-24',
    required: false,
    defaultValue: 18,
  },
  labelStyle: {
    name: 'labelStyle',
    type: 'string',
    description: '标签样式（转义的JSON字符串），示例："{"color":"red"}"',
    required: true,
  },
  labelWidth: {
    name: 'labelWidth',
    type: 'number',
    description: '标签宽度，示例：100',
    required: false,
  },
  isLongLabel: {
    name: 'isLongLabel',
    type: 'boolean',
    description: '是否为长标签，可选值：false 和 true',
    required: false,
  },
  haveEnterButton: {
    name: 'haveEnterButton',
    type: 'boolean',
    description: '是否显示搜索按钮，默认值：false，可选值：false 和 true，用于 single-input 组件',
    required: false,
    defaultValue: false,
  },
  enterButton: {
    name: 'enterButton',
    type: 'string',
    description: '搜索按钮文本，用于 single-input 组件',
    required: false,
  },
  itemStyle: {
    name: 'itemStyle',
    type: 'string',
    description: '组件样式，示例："color:red;font-size:20px"，用于 multi-input 组件',
    required: false,
  },
  autoSize: {
    name: 'autoSize',
    type: 'boolean',
    description: '是否根据内容自适应高度，默认值：true，可选值：false 和 true，用于 multi-input 组件',
    required: false,
    defaultValue: true,
  },
  rows: {
    name: 'rows',
    type: 'number',
    description:
        '多行文本行数，最小为1的整数。当 autoSize 属性为 false 时需要配置此项，当 autoSize 值为 true 时需要移除此项，默认值：2，用于 multi-input 组件',
    required: false,
    defaultValue: 2,
  },
  min: {
    name: 'min',
    type: 'number',
    description: '最小可输入值，示例：1，用于 number 组件',
    required: false,
  },
  max: {
    name: 'max',
    type: 'number',
    description: '最大可输入值，示例：100，用于 number 组件',
    required: false,
  },
  precision: {
    name: 'precision',
    type: 'number',
    description: '数字精度,小数点后位数，比如2则为.00，示例：2，用于 number 组件',
    required: false,
    defaultValue: 0,
  },
  step: {
    name: 'step',
    type: 'number',
    description: '值修改时的步长，用于 number 组件',
    required: false,
    defaultValue: 1,
  },
  asAmount: {
    name: 'asAmount',
    type: 'boolean',
    description: '是否为金额类型，可选值：false 和 true，用于 number 组件',
    required: false,
  },
  amountPre: {
    name: 'amountPre',
    type: 'string',
    description: '金额前缀。数值为金额类型时（asAmount 值为 true）此项生效，需要配置，用于 number 组件',
    required: false,
  },
  alignRight: {
    name: 'alignRight',
    type: 'boolean',
    description: '值是否右对齐，可选值：false 和 true，用于 number 组件',
    required: false,
    defaultValue: false,
  },
  decimalSeparator: {
    name: 'decimalSeparator',
    type: 'string',
    description: '小数点符号，默认值：.，用于 number 组件',
    required: false,
    defaultValue: '.',
  },
  dataType: {
    name: 'dataType',
    type: 'string',
    description: '数据填充方式，默认值：static，可选值：static/remote/customRemote，用于 rpc 组件',
    required: true,
    defaultValue: 'static',
    options: ['static', 'remote', 'customRemote'],
  },
  dropdownTrigger: {
    name: 'dropdownTrigger',
    type: 'string',
    description: '查询行为触发方式，默认值：delay，可选值：delay/enterKeyup/click，用于 rpc 组件',
    required: false,
    defaultValue: 'delay',
    options: ['delay', 'enterKeyup', 'click'],
  },
  dropdownMatchSelectWidth: {
    name: 'dropdownMatchSelectWidth',
    type: 'boolean',
    description: '下拉框与输入框同宽，默认值：false，可选值：false 和 true，用于 rpc 组件',
    required: false,
    defaultValue: false,
  },
  dropdownMatchSelectWidthValue: {
    name: 'dropdownMatchSelectWidthValue',
    type: 'string',
    description: '下拉输入框宽度，一般为带 px 单位宽度，默认值：500px，用于 rpc 组件',
    required: false,
    defaultValue: '500px',
  },
  searchDelay: {
    name: 'searchDelay',
    type: 'number',
    description: '延迟时间，当 dropdownTrigger 属性值为 delay 时，此项必须，单位毫秒，默认值：600，用于 rpc 组件',
    required: true,
    defaultValue: 600,
  },
  titleList: {
    name: 'titleList',
    type: 'Array',
    description:
        '需要展示的表头信息配置，为 JSON 格式的对象数组，对象只能包含 key 和 value 属性。支持配置多组。key 属性表示属性字段变量，value 表示字段名称，不支持其他属性格式，默认值：[{"key": "id", "value": "编号"}, {"key": "name", "value": "名称"}]，用于 rpc 组件',
    required: true,
    defaultValue: [
      {
        key: 'id',
        value: '编号',
      },
      {
        key: 'name',
        value: '名称',
      },
    ],
  },
  optionConfig: {
    name: 'optionConfig',
    type: 'object',
    description:
        '配置选中后的实际值对应的字段和显示值对应的字段。格式固定，为 JSON 对象，只能包含 value 和 label 属性，与 titleList 属性 key 关联，默认值：{"value": "id", "label": "name"}，用于 rpc 组件',
    required: true,
    defaultValue: {
      value: 'id',
      label: 'name',
    },
  },
  data: {
    name: 'data',
    type: 'string',
    description:
        '组件的数据项。格式为经过转义的标准 JSON 格式对象数组字符串。对象中的变量名称与 titleList 中配置的 key 值对应，同时与 optionConfig 中的值关联，默认值："[{"name":"张三","id":"10010"}]"，用于 rpc 组件',
    required: true,
  },
  cardHeadStyle: {
    name: 'cardHeadStyle',
    type: 'string',
    description: '标题CSS。标题的CSS样式，示例: width: 120px;height:120px;',
    required: false,
  },
  width: {
    name: 'width',
    type: 'number',
    description: '宽度。列宽度信息。',
    required: false,
  },
  size: {
    name: 'size',
    type: 'string',
    description: '组件大小，默认值：default，可选值：default(默认)/small(较小)/large(较大)',
    required: false,
    defaultValue: 'default',
    options: ['default', 'small', 'large'],
  },
  labelText: {
    name: 'labelText',
    type: 'boolean',
    description: 'Label的展示方式，为true则表示label为纯文本展示，不能编辑组件的label',
    required: false,
    defaultValue: false,
  },
  staticData: {
    name: 'staticData',
    type: 'string',
    description: '静态数据源，格式为经过转义标准的 JSON 格式对象数组字符串，对象中的变量名称与 titleList 中配置的 key 值对应，同时与 optionConfig 中的值关联，默认值："[{"name":"张三","id":"10010"}]"，用于 rpc 组件',
    required: false,
  },
  // FIX ME
  format: {
    name: 'format',
    type: 'string',
    description: '格式化格式',
    required: false,
    defaultValue: 'YYYY-MM-DD',
  },
  validNowTime: {
    name: 'validNowTime',
    type: 'boolean',
    description: '是否只显示当前时间之后的时间，默认值：false，可选值：false 和 true，用于 datePicker 、timePicker 、dateTimePicker 、dateRangePicker 、timeRangePicker 、dateTimeRangePicker 组件',
    required: false,
    defaultValue: false,
  }
};

const ComponentsProps:Record<string, ComponentProp> = {
  div: {
    type: 'div',
    props: [
      CommonProps.type,
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.tools,
    ],
  },
  tabs: {
    type: 'tabs',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.tools,
      CommonProps.staticData,
      CommonProps.size,
      CommonProps.labelText,
    ],
  },
  collapse: {
    type: 'collapse',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.tools,
      CommonProps.staticData
    ],
  },
  card: {
    type: 'card',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.tools,
    ],
  },
  drawer: {
    type: 'drawer',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.tools,
    ],
  },
  modal: {
    type: 'modal',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.tools,
    ],
  },
  'border-layout': {
    type: 'border-layout',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.tools,
      CommonProps.dataType,
      CommonProps.staticData,
    ],
  },
  search: {
    type: 'search',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.tools,
    ],
  },
  'single-input': {
    type: 'single-input',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.placeholder,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules,
      CommonProps.validateTrigger,
      CommonProps.allowClear,
      CommonProps.addonBefore,
      CommonProps.addonAfter,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  'input-group': {
    type: 'input-group',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.size,
      CommonProps.staticData,
    ],
  },
  'input-search': {
    type: 'input-search',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.haveEnterButton,
      CommonProps.placeholder,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
      CommonProps.enterButton,
    ],
  },
  password: {
    type: 'password',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.placeholder,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules_object,
      CommonProps.validateTrigger,
      CommonProps.allowClear,
      CommonProps.addonBefore,
      CommonProps.addonAfter,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  'multi-input': {
    type: 'multi-input',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.autoSize,
      CommonProps.placeholder,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules,
      CommonProps.validateTrigger,
      CommonProps.itemStyle,
      CommonProps.rows,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  number: {
    type: 'number',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.decimalSeparator,
      CommonProps.placeholder,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules_object,
      CommonProps.validateTrigger,
      CommonProps.min,
      CommonProps.max,
      CommonProps.precision,
      CommonProps.step,
      CommonProps.asAmount,
      CommonProps.amountPre,
      CommonProps.alignRight,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  rpc: {
    type: 'rpc',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.dataType,
      CommonProps.placeholder,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.allowClear,
      CommonProps.dropdownTrigger,
      CommonProps.dropdownMatchSelectWidth,
      CommonProps.dropdownMatchSelectWidthValue,
      CommonProps.searchDelay,
      CommonProps.titleList,
      CommonProps.optionConfig,
      CommonProps.data,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  switch: {
    type: 'switch',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  radio: {
    type: 'radio',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.dataType,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.validateTrigger,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  checkbox: {
    type: 'checkbox',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.dataType,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules_object,
      CommonProps.validateTrigger,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  select: {
    type: 'select',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.dataType,
      CommonProps.placeholder,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules_object,
      CommonProps.validateTrigger,
      CommonProps.allowClear,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  cascader: {
    type: 'cascader',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.dataType,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules_object,
      CommonProps.validateTrigger,
      CommonProps.allowClear,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  tree: {
    type: 'tree',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.dataType,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules_object,
      CommonProps.validateTrigger,
      CommonProps.allowClear,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  rate: {
    type: 'rate',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  slider: {
    type: 'slider',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.step,
      CommonProps.min,
      CommonProps.max,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  color: {
    type: 'color',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  photo: {
    type: 'photo',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  upload: {
    type: 'upload',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  transfer: {
    type: 'transfer',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.dataType,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.staticData,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  year: {
    type: 'year',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules_object,
      CommonProps.validateTrigger,
      CommonProps.allowClear,
      CommonProps.format,
      CommonProps.validNowTime,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  quarter: {
    type: 'quarter',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules_object,
      CommonProps.validateTrigger,
      CommonProps.allowClear,
      CommonProps.format,
      CommonProps.validNowTime,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  month: {
    type: 'month',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules_object,
      CommonProps.validateTrigger,
      CommonProps.allowClear,
      CommonProps.format,
      CommonProps.validNowTime,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  week: {
    type: 'week',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules_object,
      CommonProps.validateTrigger,
      CommonProps.allowClear,
      CommonProps.format,
      CommonProps.validNowTime,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  date: {
    type: 'date',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules_object,
      CommonProps.validateTrigger,
      CommonProps.allowClear,
      CommonProps.format,
      CommonProps.validNowTime,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  time: {
    type: 'time',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules_object,
      CommonProps.validateTrigger,
      CommonProps.allowClear,
      CommonProps.format,
      CommonProps.validNowTime,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  datetime: {
    type: 'datetime',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules_object,
      CommonProps.validateTrigger,
      CommonProps.allowClear,
      CommonProps.format,
      CommonProps.validNowTime,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  daterange: {
    type: 'daterange',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules_object,
      CommonProps.validateTrigger,
      CommonProps.allowClear,
      CommonProps.format,
      CommonProps.validNowTime,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  datetimerange: {
    type: 'datetimerange',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.disabled,
      CommonProps.required,
      CommonProps.initialValue,
      CommonProps.fieldsAlias,
      CommonProps.extra,
      CommonProps.message,
      CommonProps.rules_object,
      CommonProps.validateTrigger,
      CommonProps.allowClear,
      CommonProps.format,
      CommonProps.validNowTime,
      CommonProps.isRender,
      CommonProps.labelCol,
      CommonProps.wrapperCol,
      CommonProps.labelStyle,
      CommonProps.labelWidth,
      CommonProps.isLongLabel,
    ],
  },
  richText: {
    type: 'richText',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
    ],
  },
  echarts: {
    type: 'echarts',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.dataType,
      CommonProps.style
    ],
  },
  dynamic: {
    type: 'dynamic',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.dataType,
      CommonProps.tools,
    ],
  },
  bigTable: {
    type: 'bigTable',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.labelText,
      CommonProps.itemStyle,
      CommonProps.size,
      CommonProps.dataType,
      CommonProps.data,
      CommonProps.tools,
    ],
  },
  span: {
    type: 'span',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.labelText,
      CommonProps.tools,
    ],
  },
  p: {
    type: 'p',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.labelText,
      CommonProps.tools,
    ],
  },
  steps: {
    type: 'steps',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.size,
      CommonProps.staticData,
      CommonProps.dataType,
      CommonProps.tools,
    ],
  },
  timeline: {
    type: 'timeline',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.staticData,
      CommonProps.dataType,
      CommonProps.style,
      CommonProps.tools,
    ],
  },
  'e-tree': {
    type: 'e-tree',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.autoShow,
      CommonProps.labelText,
      CommonProps.itemStyle,
      CommonProps.dataType,
      CommonProps.staticData,
      CommonProps.tools,
    ],
  },
  iframe: {
    type: 'iframe',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.labelText,
      CommonProps.itemStyle,
      CommonProps.tools,
    ],
  },
  'tree-modal': {
    type: 'tree-modal',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.width,
      CommonProps.display,
      CommonProps.dataType,
      CommonProps.allowClear,
      CommonProps.staticData,
      CommonProps.tools,
    ],
  },
  space: {
    type: 'space',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.labelText,
      CommonProps.display,
      CommonProps.tools,
    ],
  },
  divider: {
    type: 'divider',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.display,
      CommonProps.itemStyle,
      CommonProps.tools,
    ],
  },
  'label-con': {
    type: 'label-con',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.labelCol,
      CommonProps.display,
      CommonProps.tools,
    ],
  },
  button: {
    type: 'button',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.size,
      CommonProps.display,
      CommonProps.tools,
    ],
  },
  'button-label': {
    type: 'button-label',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.size,
      CommonProps.display,
      CommonProps.tools,
    ],
  },
  'button-group': {
    type: 'button-group',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.dataType,
      CommonProps.display,
      CommonProps.staticData,
      CommonProps.tools,
    ],
  },
  report: {
    type: 'report',
    props: [
      CommonProps.fieldDecoratorId,
      CommonProps.renderId,
      CommonProps.css,
      CommonProps.style,
      CommonProps.display,
      CommonProps.label,
      CommonProps.span,
      CommonProps.display,
      CommonProps.labelText,
      CommonProps.tools,
    ],
  },
};

export default ComponentsProps;
